server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample_db
    username: ashiras
    password: ASHIRAS
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    # hibernate:
    #   ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE